server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/clientes/**
        - id: ms-vehiculos
          uri: lb://ms-vehiculos
          predicates:
            - Path=/api/vehiculos/**,/api/tipos-vehiculo/**
        - id: ms-espacios
          uri: lb://ms-espacios
          predicates:
            - Path=/api/espacios/**
        - id: ms-reservas
          uri: lb://ms-reservas
          predicates:
            - Path=/api/reservas/**
        - id: ms-accesos
          uri: lb://ms-accesos
          predicates:
            - Path=/api/accesos/**
        - id: ms-tarifas
          uri: lb://ms-tarifas
          predicates:
            - Path=/api/tarifas/**
        - id: ms-pagos
          uri: lb://ms-pagos
          predicates:
            - Path=/api/pagos/**
        - id: ms-reportes
          uri: lb://ms-reportes
          predicates:
            - Path=/api/reportes/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/