server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: false
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/clientes/**,/api/tipo-cliente/**
        - id: ms-vehiculos
          uri: lb://ms-vehiculos
          predicates:
            - Path=/api/vehiculos/**,/api/tipos-vehiculo/**
        - id: ms-espacios
          uri: lb://ms-espacios
          predicates:
            - Path=/api/espacios/**,/api/tipo-espacio/**
        - id: ms-reservas
          uri: lb://ms-reservas
          predicates:
            - Path=/api/reservas/**
        - id: ms-accesos
          uri: lb://ms-accesos
          predicates:
            - Path=/api/accesos/**
        - id: ms-tarifas
          uri: lb://ms-tarifas
          predicates:
            - Path=/api/tarifas/**,/api/horarios-tarifa/**
        - id: ms-pagos
          uri: lb://ms-pagos
          predicates:
            - Path=/api/cobros/**,/api/bancos/**,/api/metodos-pago/**,/api/tipo-tarjetas/**
        - id: ms-reportes
          uri: lb://ms-reportes
          predicates:
            - Path=/api/reportes/**
        - id: security-service
          uri: lb://security-service
          predicates:
            - Path=/api/permisos/**,/api/roles-permisos/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: acosiYPShfbW/MKtcBHBLNRQZHCN5ENrLFUb0ZPlHmI=