spring.application.name=ms-reportes
server.port=8090

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
# Swagger / OpenAPI (springdoc) - Guia 3.1.2 Unidad 3
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui/index.html
