spring.application.name=eureka-server

# Puerto estándar para Eureka
server.port=8761

# Configuraciones para que el servidor no actúe como cliente de sí mismo
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Configuración de log para ver cuando los microservicios se conectan
logging.level.com.netflix.eureka=INFO
logging.level.com.netflix.discovery=INFO