    spring.application.name=eureka-server

    # Puerto estandar para eureka
    server.port=8761

    #Configuraciones para qie el servidor no actue como cliente de si mismo
    eureka.client.register-with-eureka=false
    eureka.client.fetch-registry=false

    #Configuracion de logs
    logging.level.com.netflix.eureka=INFO
    logging.level.com.netflix.discovery=INFO