spring.application.name=ms-vehiculos
server.port=8084

#conexion a DB Vehiculos

## FALTA CREAR ESTA BASE DE DATOS EN mySQL ##
spring.datasource.url = jdbc:mysql://localhost:3307/db_vehiculos
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

#registro en Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
